gateway_ip: 192.168.1.253
username: admin
password: admin
cookie: "1723892300"  # This will be populated automatically after successful login

devices:
  Living_room1:
    location: Living_room
    type: DIMMER
    entity:
      addr: 0
      addrMode: 2
      epId: 10

  SW01-1:
    location: Living_room
    type: SWITCH
    entity:
      addr: 12018
      addrMode: 2
      epId: 10

  SW01-2:
    location: Entrance/Kitchen
    type: SWITCH
    entity:
      addr: 12018
      addrMode: 2
      epId: 11

  SW02-1:
    location: Bed_room
    type: SWITCH
    entity:
      addr: 45059
      addrMode: 2
      epId: 10

  SW02-2:
    location: Bed_room
    type: SWITCH
    entity:
      addr: 45059
      addrMode: 2
      epId: 11

  AC01:
    location: Living_room
    type: AC
    entity:
      addr: 20545
      addrMode: 2
      epId: 1
    ir_codes:
      power_on: []  # Add the actual IR code for power on
      power_off: [] # Add the actual IR code for power off
      cool_mode: [] # Add the IR code for cool mode
      heat_mode: [] # Add the IR code for heat mode
      # Add more IR codes for different temperatures, fan speeds, etc.